TrajectoryPlannerROS:
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 3.2
  max_vel_x: 0.3
  min_vel_x: 0.0
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4
  sim_time: 1.7
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  pdist_scale: 0.6
  gdist_scale: 0.6
  occdist_scale: 0.02
  oscillation_reset_dist: 0.05
  escape_reset_dist: 0.10
  escape_reset_theta: pi/2
  vx_samples: 20
  vtheta_samples: 20
  heading_lookahead: 0.325
  holonomic_robot: true
  escape_vel: -0.1
  dwa: false
  heading_scoring: false
  heading_scoring_timestep: 0.1
  simple_attractor: false
  y_vels: "-0.3,-0.1,0.1,-0.3"
  restore_defaults: false
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.10
  meter_scoring: false
