plugins:
#- name: static
#  type: clutter_2d::StaticLayer
- name: obstacles
  type: clutter_2d::ObstacleLayer
- name: inflation
  type: clutter_2d::InflationLayer
obstacles:
  observation_sources: point_cloud_sensor # laser_scan
  point_cloud_sensor:
    sensor_frame: kinect_depth_optical_frame
    data_type: PointCloud2
    topic: /kinect/depth_registered/points
    marking: true
    clearing: true
    min_obstacle_height: 0.001    
    obstacle_range: 2.5
    raytrace_range: 2.5
  laser_scan:
    sensor_frame: hokuyo_link
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true    
    obstacle_range: 2.5
    raytrace_range: 2.5
  track_unknown_space: false
inflation:
  inflation_radius: 0.55

static:
  track_unknown_space: false
  use_maximum: false
  inflation_radius: 0.55
  robot_radius: 0.225
  cost_scaling_factor: 10
  with_inflation: false
