local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 20.0
  publish_frequency: 3.0
  static_map: false
  rolling_window: true
  width: 5
  height: 5
  resolution: 0.051510000000
  track_unknown_space: false
  robot_radius: 0.225
