controller_frequency: 10.0
controller_patience: 20.0
planner_frequency: 1
planner_patience: 5.0
shutdown_costmaps: false
#robot_radius:  0.225
recovery_behavior_enabled: false #STEFAN
oscillation_timeout: 0 #STEFAN
