LocalPlanner: {
  verbose: false,
  max_linear_vel: 0.7,
  max_angular_vel: 1.0,
  xy_goal_tolerance: 0.10,
  yaw_goal_tolerance: 0.10,
  odom_topic: "/odom",
#  controller/P_linear: 1.25,
#  controller/P_angular: 1.05,
#  controller/I_linear: 0.05,
#  controller/I_angular: 0.05,
#  controller/D_linear: 0.1,
#  controller/D_angular: 0.1,
#  controller/delay: 0.0,
  controller/P_linear: 3.00,
  controller/P_angular: 3.00,
  controller/I_linear: 0.0,
  controller/I_angular: 0.0,
  controller/D_linear: 0.000,
  controller/D_angular: 0.000,
  controller/delay: 0.0,
}