root_path: /home/sosswald/catkin/peter_ws2/src/simulation_dev/simulated_navigation_launch/scripts/object_singlecluster_twoways           #must exist
folder_name: cluster_density_0.7                     #must exist as {root_path}/{folder_name}_#
file_name: object_location
model_0_name: orange_box_30cm_static
model_1_name: orange_box_60cm_static
model_2_name: orange_box_120cm_static
model_3_name: ""
model_4_name: ""
map_count: 20

cluster_count_min: 1
cluster_count_max: 1
cluster_radius_min: 12.0
cluster_radius_max: 12.0
cluster_object_density_min: 0.7
cluster_object_density_max: 0.7
cluster_xmin: 15.0
cluster_xmax: 15.0
cluster_ymin: 6.1
cluster_ymax: 6.1
cluster_min_distance: 6.5

spawn_xmin: 3.0
spawn_xmax: 26.0
spawn_ymin: 2.0
spawn_ymax: 10.0
spawn_zmin: 0.0
spawn_zmax: 0.0
spawn_yawmin: 0.0
spawn_yawmax: 180.0

object_0_corner_x: 0.15
object_0_corner_y: 0.05
object_1_corner_x: 0.3
object_1_corner_y: 0.05
object_2_corner_x: 0.6
object_2_corner_y: 0.05
object_3_corner_x: 0.0
object_3_corner_y: 0.0
object_4_corner_x: 0.0
object_4_corner_y: 0.0