<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
       name="simple_room">

  <xacro:include filename="$(find robotino_gazebo_worlds)/urdf/materials.urdf.xacro" />
  <xacro:include filename="$(find robotino_gazebo_worlds)/urdf/common.xacro" />

  <property name="size_total_x" value="5.0" />
  <property name="size_total_y" value="5.0" />
  <property name="wall_depth" value="0.1" />
  <property name="size_z_wall" value="1" />
  
  <xacro:macro name="simple_room" params="name">
  
  
  <!--gazebo>
    <plugin name="environment_gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>world</robotNamespace>
      <robotParam>/world_description</robotParam>
    </plugin>
  </gazebo-->

  <!-- world -->
  <link name="world"/>

  <!-- walls -->
  <!-- wall_00 -->
  <link name="wall_00">
    <xacro:box_inertial x="${size_total_x}" y="${wall_depth}" z="${size_z_wall}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${size_total_x} ${wall_depth} ${size_z_wall}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${size_total_x} ${wall_depth} ${size_z_wall}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_00">
    <material>ROBOTINO/Wall</material>
  </gazebo>

  <joint name="joint_wall_00" type="fixed">
    <origin xyz="0.0 ${-size_total_x/2+wall_depth/2} ${size_z_wall/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_00" />
  </joint>

  <!-- wall_01 -->
  <link name="wall_01">
    <xacro:box_inertial x="${wall_depth}" y="${size_total_y}" z="${size_z_wall}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_total_y} ${size_z_wall}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_total_y} ${size_z_wall}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_01">
    <material>ROBOTINO/Wall</material>
  </gazebo>

  <joint name="joint_wall_01" type="fixed">
    <origin xyz="${size_total_x/2-wall_depth/2} 0.0 ${size_z_wall/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_01" />
  </joint>

  <!-- wall_02 -->
  <link name="wall_02">
    <xacro:box_inertial x="${size_total_x}" y="${wall_depth}" z="${size_z_wall}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${size_total_x} ${wall_depth} ${size_z_wall}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${size_total_x} ${wall_depth} ${size_z_wall}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_02">
    <material>ROBOTINO/Wall</material>
  </gazebo>

  <joint name="joint_wall_02" type="fixed">
    <origin xyz="0.0 ${size_total_x/2-wall_depth/2} ${size_z_wall/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_02" />
  </joint>


  <!-- wall_03 -->
  <link name="wall_03">
    <xacro:box_inertial x="${wall_depth}" y="${size_total_y}" z="${size_z_wall}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_total_y} ${size_z_wall}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_total_y} ${size_z_wall}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_03">
    <material>ROBOTINO/Wall</material>
  </gazebo>

  <joint name="joint_wall_03" type="fixed">
    <origin xyz="-${size_total_x/2+wall_depth/2} 0.0 ${size_z_wall/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_03" />
  </joint>
  
  
  </xacro:macro>

  <xacro:simple_room name="simple_room" />

</robot>

